version: '3.9'

volumes:
  postgres-data:
    name: fastify-postgres-data
    
services:
  pg:
    container_name: fastify-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${USER}
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  